#!/usr/bin/env python3
"""Generate the authoritative tool table FROM the registry.

Four contradictory tool counts once coexisted across API.md/README/live
server/registry. This script makes the registry the single source: the
table in docs/API.md is generated, and --check fails CI when they drift.

Usage:
    python scripts/dump_tool_table.py           # print the markdown table
    python scripts/dump_tool_table.py --write   # update docs/API.md in place
    python scripts/dump_tool_table.py --check   # exit 1 if docs drifted
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from ewsmcp.tools import calendar_people, mail_read, tasks, writes  # noqa: E402
from ewsmcp.tools.base import CLASS_TIER  # noqa: E402

API_MD = Path(__file__).resolve().parents[1] / "docs" / "API.md"
START = "<!-- TOOL_TABLE_START (generated by scripts/dump_tool_table.py) -->"
END = "<!-- TOOL_TABLE_END -->"


def _first_sentence(text: str) -> str:
    text = " ".join((text or "").split())
    for stop in (". ", "; "):
        idx = text.find(stop)
        if idx > 0:
            return text[: idx + 1].rstrip()
    return text[:140]


def build_table() -> str:
    packs = [
        ("mail-read", mail_read.TOOLS),
        ("calendar / people / status", calendar_people.TOOLS),
        ("tasks / waiting-on", tasks.TOOLS),
        ("writes", writes.TOOLS),
        ("semantic (only when EWS_SEMANTIC_INDEX != none)",
         mail_read.SEMANTIC_TOOLS),
    ]
    core = sum(len(t) for _n, t in packs[:4])
    lines = [
        f"**{core} tools** in the default registry "
        f"(+{len(mail_read.SEMANTIC_TOOLS)} with the semantic tier). "
        "Capability tiers: read ⊂ draft ⊂ full — a tool is available when "
        "the server tier is at or above its minimum.",
        "",
        "| tool | class | min tier | what it does |",
        "|---|---|---|---|",
    ]
    for pack_name, specs in packs:
        for spec in specs:
            lines.append(
                f"| `{spec.name}` | {spec.side_effect_class} "
                f"| {CLASS_TIER.get(spec.side_effect_class, 'draft')} "
                f"| {_first_sentence(spec.description)} |"
            )
    return "\n".join(lines)


def main() -> int:
    table = build_table()
    if len(sys.argv) == 1:
        print(table)
        return 0
    if not API_MD.exists():
        print(f"missing {API_MD}")
        return 2
    content = API_MD.read_text(encoding="utf-8")
    if START not in content or END not in content:
        print(f"markers missing in {API_MD}")
        return 2
    head, _, rest = content.partition(START)
    _, _, tail = rest.partition(END)
    regenerated = f"{head}{START}\n{table}\n{END}{tail}"
    if sys.argv[1] == "--write":
        API_MD.write_text(regenerated, encoding="utf-8", newline="\n")
        print(f"updated {API_MD}")
        return 0
    if sys.argv[1] == "--check":
        if content != regenerated:
            print("docs/API.md tool table DRIFTED from the registry — "
                  "run scripts/dump_tool_table.py --write")
            return 1
        print("docs/API.md tool table matches the registry")
        return 0
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main())
